# Generated by Django 2.2 on 2021-08-01 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('fav_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='add_to_fav_by',
            field=models.ManyToManyField(related_name='fav_books', to='login.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='login.User'),
            preserve_default=False,
        ),
    ]
